version: '3.8'

services:
  utilisateur-service:
    build: .
    container_name: utilisateur-service
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=mysql+pymysql://root:password@db/utilisateur_db
    depends_on:
      - mysql-db
    command: flask run --host=0.0.0.0 --port=5000

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: utilisateur_db
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data:
